llm_providers:
  openai:
    api_key: "YOU_API_KEY"
store:
  collection_name: "DATABASE_NAME_FOR_EXEMPLAR"
  address: "QDRANT_SERVER_ADDRESS"
  embedding_model_name: "all-MiniLM-L6-v2"
classifier:
  model_path: "data/model"
data:
  dataset_path: "YOUR_DATASET_PATH"
  index_path: "data"
